### ISSUE TITLE
是否支持单独屏蔽政治词汇

### ISSUE THREAD

**Issue by xiaoluofa** [HaHaWTH/AdvancedSensitiveWords#3]

**Comment by HaHaWTH** [comment]
分词工作量比较大，之后可能会搞，这东西得一个一个打tag

**Comment by xiaoluofa** [comment]
> r

![image](https://github.com/HaHaWTH/AdvancedSensitiveWords/assets/75927411/91e60fe5-5a75-4db9-8920-4abd2157478b)
tu突然释怀的笑了哈哈哈

**Comment by HaHaWTH** [comment]
> > r
> 
> ![image](https://private-user-images.githubusercontent.com/75927411/309473404-91e60fe5-5a75-4db9-8920-4abd2157478b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzODMxODIsIm5iZiI6MTcwOTM4Mjg4MiwicGF0aCI6Ii83NTkyNzQxMS8zMDk0NzM0MDQtOTFlNjBmZTUtNWE3NS00ZGI5LTg5MjAtNGFiZDIxNTc0NzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDEyMzQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1Y2ZkNGQ2NjdkM2FkNzNhZmQ5NTA4NDhkN2UzMWNhMGE2ZTc5MTVjMTlkNTk3ODc2YmVjOTE5MGI1ZjI2NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d4gy88hvCyNKkZQPFXyPyG_pDrYR0qLY_dOl7JmpH6Y) tu突然释怀的笑了哈哈哈

试试加下指令白名单

**Comment by HaHaWTH** [comment]
或者直接把白名单反转成黑名单，加上要检测的指令

**Comment by HaHaWTH** [comment]
词库最近优化好几遍了，如有什么不足之处还请指出，感谢大佬支持🙏

**Comment by xiaoluofa** [comment]
> 词库最近优化好几遍了，如有什么不足之处还请指出，感谢大佬支持🙏

加油持续关注，那个屏蔽报错插件很好用，folia太多报错了。

**Comment by HaHaWTH** [comment]
> > 词库最近优化好几遍了，如有什么不足之处还请指出，感谢大佬支持🙏
> 
> 武器也是敏感词，应该要删一下，词库还要过滤

麻烦问下检测性能怎么样嘞，有没有卡顿之类的

**Comment by xiaoluofa** [comment]
> > > 词库最近优化好几遍了，如有什么不足之处还请指出，感谢大佬支持🙏
> > 
> > 
> > 武器也是敏感词，应该要删一下，词库还要过滤
> 
> 麻烦问下检测性能怎么样嘞，有没有卡顿之类的

没感觉到卡顿

**Comment by xiaoluofa** [comment]
bug来了，使用热卸载会直接干碎所有插件

**Comment by HaHaWTH** [comment]
> bug来了，使用热卸载会直接干碎所有插件

请问是插件内置重载还是Plugman等的重载呢，还有插件版本是

**Comment by xiaoluofa** [comment]
> > bug来了，使用热卸载会直接干碎所有插件
> 
> 请问是插件内置重载还是Plugman等的重载呢，还有插件版本是 请尝试更新至最新版本试试 [4d1f1c8](https://github.com/HaHaWTH/AdvancedSensitiveWords/commit/4d1f1c817393dcfd11462956427fb060af712969)

plugman

**Comment by HaHaWTH** [comment]
> > > bug来了，使用热卸载会直接干碎所有插件
> > 
> > 
> > 请问是插件内置重载还是Plugman等的重载呢，还有插件版本是 请尝试更新至最新版本试试 [4d1f1c8](https://github.com/HaHaWTH/AdvancedSensitiveWords/commit/4d1f1c817393dcfd11462956427fb060af712969)
> 
> plugman

插件版本是
