### ISSUE TITLE
[feature request] add multiple-message check

### ISSUE THREAD

**Issue by quiquelhappy** [HaHaWTH/AdvancedSensitiveWords#32]
hello,
a way to bypass the system is to send the word(s) on different messages, ie
> badw

> ord

> other message

please add a way to consider chat messages to be checked as appended phrases with both a separator and without (the system should check for both [badw ord other message] [badword other message] [badw ordother message] [badwordothermessage])

the amount of chat messages to be check should be configurable but of course add a heads up to the config because if the checks are done as described (I believe its the best way), they grow ^n

**Comment by HaHaWTH** [comment]
Ah, we already have it, enable chatContextCheck in config.yml and that's it ( ´▽` )
