### ISSUE TITLE
running Velocity commands

### ISSUE THREAD

**Issue by rbos** [HaHaWTH/AdvancedSensitiveWords#34]
Hi,

I want to run a command on the Velocity proxy instead of on the server. How do I do that?

for instance:

```
punishment:
- COMMAND|tempban %player 1d
```

should run on the proxy, NOT the server.

**Comment by HaHaWTH** [comment]
Added in commit 250b6a2

Now you can use `COMMAND_PROXY|tempban %player% 1d` to achieve this:)

**Comment by HaHaWTH** [comment]
Included in 1.0 version
