### ISSUE TITLE
swear in commands

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [HaHaWTH/AdvancedSensitiveWords#52]
i cannot block swear in commands.

**Comment by TDMidkwhatisxd** [comment]
not working, idk what to do

**Comment by TDMidkwhatisxd** [comment]
i used chatmanager to fix :(

**Comment by HaHaWTH** [comment]
Only commands in the commandWhitelist configuration(default inverted to blacklist) will be checked. You can add them.
